#ifndef _EEPROM_H
#define _EEPROM_H

#define EEPROM_ACCELEROMETER_X_OFFSET (0x0000)
#define EEPROM_ACCELEROMETER_Y_OFFSET (0x0002)
#define EEPROM_ACCELEROMETER_Z_OFFSET (0x0004)
#define EEPROM_GYRO_X_OFFSET (0x0006)
#define EEPROM_GYRO_Y_OFFSET (0x0008)
#define EEPROM_GYRO_Z_OFFSET (0x000A)

#endif //_EEPROM_H